In [2]:
import torch

# 1D Array

In [3]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [4]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [5]:
print(t[0], t[-1])

tensor(0.) tensor(6.)


In [6]:
a = torch.FloatTensor([0.])
print(a)

tensor([0.])


In [7]:
print(t[:2], t[3:])

tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [8]:
print(t[4:-1])

tensor([4., 5.])


# 2D Array

In [9]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                       ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [12]:
print(t.dim()) #rank (차원)
print(t.size()) #size -> a by b

2
torch.Size([4, 3])


In [13]:
print(t[:, 1]) # 첫번째 차원에서는 다 가져옴
print(t[:, 1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [16]:
print(t[:, 0:2].size())
print(t[:, 0:2])

torch.Size([4, 2])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


# Matrix 연산 규칙

## Broacasting

In [18]:
## 자동으로 사이즈 맞춰주는 역할 -> 조심히 사용하자.
## matrix 연산이니 2차원.

# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [19]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([[4., 5.]])


In [21]:
# 2x1 Vector + 1x2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## Multiplication **VS** Matrix Multiplication

In [23]:
## Matrix Multiplication = 행렬 곱셈
## matmul() 사용

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 by 2
print('Shape of Matrix 2: ', m2.shape) # 2 by 1
print(m1.matmul(m2)) # 2 by 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [26]:
## Multiplication = 값 곱셈
## 확장 후 각 위치에 있는 값끼리 값 곱셈
# * 사용

print(m1 * m2)

tensor([[1., 2.],
        [6., 8.]])


## Mean

In [27]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [29]:
t = torch.LongTensor([1, 3]) # mean 함수는 float type에만 사용할 수 있다.
try:
  print(t.mean())
except Exception as exc:
  print(exc)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [30]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())
print(t.mean(dim = 0)) # 0번 차원에 대해 평균
print(t.mean(dim = -1)) # 마지막번 = 가장 안쪽에 대한 평균

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])


## SUM

In [31]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.sum())
print(t.sum(dim = 1))

tensor(10.)
tensor([3., 7.])


## Max AND Argmax

In [32]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.max())
print(t.max(dim = 0)) # 최대값과 그 값이 나온 인덱스를 함께 반환

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [33]:
print("Max: ", t.max(dim=0)[0])
print("Argmax: ", t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


## View (numpy - Reshape)

In [36]:
import numpy as np
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])

In [37]:
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [40]:
print(ft.view([-1, 3])) # 2x2x3 -> ?x3 -> 4x3
print(ft.view([-1, 3]).shape)
print(ft.view([-1, 1, 3])) # 2x2x3 -> ?x1x3 -> 4x1x3
print(ft.view([-1, 1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze

In [41]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [44]:
## 해당 dimension의 element가 1일때 없애줌
# 3x1 -> 3
ft.squeeze(dim = 0)
# ft = 3x1
# dim = 0 이 3이므로(1이 아님) 변화 x

tensor([[0.],
        [1.],
        [2.]])

In [45]:
ft.squeeze(dim = 1)

tensor([0., 1., 2.])

## Unsqueeze

In [46]:
## 원하는 dimension에 1 을 넣어줌

ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [47]:
print(ft.unsqueeze(0)) # dimension 0 에 1 추가 -> (3 -> 1by3)

tensor([[0., 1., 2.]])


In [48]:
ft.view(1, -1) # 1by3 -> 1by? -> 1by3

tensor([[0., 1., 2.]])

In [49]:
ft.unsqueeze(1) # dimension 1에 1 추가 -> 3 -> 3by1

tensor([[0.],
        [1.],
        [2.]])

## Type Casting

In [50]:
lt = torch.LongTensor([1, 2, 3, 4]) # Int

In [51]:
lt.float() # float

tensor([1., 2., 3., 4.])

In [52]:
bt = torch.ByteTensor([True, False, False, True]) # Boolean

In [53]:
bt.long() #Int

tensor([1, 0, 0, 1])

In [54]:
bt.float()

tensor([1., 0., 0., 1.])

In [55]:
bt

tensor([1, 0, 0, 1], dtype=torch.uint8)

## Concatenate (사슬)

In [3]:
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5,6], [7,8]])

In [5]:
print(torch.cat([x, y], dim=0)) #0번째 차원이 늘어남 => (2by2 -> 4by2)
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [6]:
torch.cat([x, y]) # default 값이 0인가보다.

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

## Stacking

In [9]:
## cat은 붙여서 늘려나간다면, stack은 차원이 늘어난다. ( -> 즉 쌓는 개념)
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z])) # 2 -> 3by2
print(torch.stack([x, y, z], dim = 1)) # 2 -> 2by3

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


## Ones and Zeros

In [10]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])

In [11]:
torch.ones_like(x) # 1이 아닌것을 1로

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.zeros_like(x) # 0이 아닌것을 0으로

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## In-place Operation

In [13]:
x = torch.FloatTensor([[0, 2], [3, 4]])

In [14]:
print(x.mul(2))
print(x)

tensor([[0., 4.],
        [6., 8.]])
tensor([[0., 2.],
        [3., 4.]])


In [15]:
print(x.mul_(2)) # 메모리에 새로 선언하지 않고 기존 메모리 주소에 할당.
print(x)

tensor([[0., 4.],
        [6., 8.]])
tensor([[0., 4.],
        [6., 8.]])


In [16]:
print(x.add(1))
print(x)

tensor([[1., 5.],
        [7., 9.]])
tensor([[0., 4.],
        [6., 8.]])


In [17]:
print(x.add_(1))
print(x)

tensor([[1., 5.],
        [7., 9.]])
tensor([[1., 5.],
        [7., 9.]])
